"""more migrations

Revision ID: 0517d59de319
Revises: 
Create Date: 2022-05-11 23:26:38.905563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0517d59de319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch')
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('date', sa.DateTime(timezone=250), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'time')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_pitches_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitches_id_fkey', 'users', 'pitches', ['pitches_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.add_column('pitches', sa.Column('time', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'date')
    op.drop_column('pitches', 'title')
    op.create_table('pitch',
    sa.Column('id', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
